### ISSUE TITLE
How to use with other init system?

### ISSUE THREAD

**Issue by FranklinYu** [jjk-jacky/anopa#10]
We can use s6 [without replacing init system](https://skarnet.org/software/s6/s6-svscan-not-1.html). Is there anything similar in anopa?

**Comment by jjk-jacky** [comment]
Apples & oranges. That is to say, you're comparing things that aren't
the same at all, so the comparison doesn't make much sense.

IOW, you can use s6 with any init system because it isn't one and
doesn't aim to be (s6-svscan can be used as PID1, yes, but that's
still not an init system).

anopa on the other hand (is build around s6, and) aims to provide that
functionality (init) as well (as that of a service manager); So you can
use the provided scripts as init system. Of course you're free to tweak
them as you need, or indeed use another init system of your choosing --
of course then you'll have to work out the interactions between said
init & anopa (in its capacity of service manager).

As described in the man page(s), the init part of anopa consist of a
few simple (execline) scripts, so it should be pretty easy to see how
they work, tweak them as needed or even replace them altogether.

HTH,

**Comment by FranklinYu** [comment]
The current deployment of s6, according to the author, is to directly link service configurations to scan directory, which will leave the supervisor and event folders after s6 exits. I like anopa copying the configuration (`/etc/anopa/services/`) to the service directory (`/run/services/`) so the configuration can be made read-only, and `/run/` can be made tmpfs.

Is there any other project that you have heard of, doing this job for non-init case? I understand that I can simply DIY but it would be awesome if this already exists.

**Comment by jjk-jacky** [comment]
Well, you can use s6 however you want, i.e. you can either use your
scandir directly, or - as anopa does indeed - use a copy into a tmpfs
first.

But that's not limited to anopa, you could do so manually, or even use
some other tool of the s6 family. s6-rc[1] for instance is another
service manager for s6, with which you can also have your scandir in a
tmpfs.

In fact, then there's also s6-linux-init[2] which would be the init
part, setting up things to use s6-rc as service manager. And though I
haven't use it personally, I'm quite sure it uses the same idea of
copying the db/scandir into a tmpfs on boot, then using that.

Now it is obviously intended for use as init, but you might want to
have a look anyway, it might be possible to use (some of) it in a
non-init case, or just as inspiration.


[1] https://skarnet.org/software/s6-rc/
[2] https://skarnet.org/software/s6-linux-init/

**Comment by FranklinYu** [comment]
`s6-rc` seems to be the thing I was looking for. Thanks! I'll contact the author of `s6` family for more help.
