### ISSUE TITLE
deps.mak file missing

### ISSUE THREAD

**Issue by cavemandaveman** [jjk-jacky/anopa#4]
`configure` was successful, but when trying to build, I am getting the following error on Alpine Linux:

``` shell
# make
Makefile:20: package/deps.mak: No such file or directory
make: *** No rule to make target 'package/deps.mak'.  Stop.
```

**Comment by jjk-jacky** [comment]
Right, I assume you're trying to build from git, not the tarball, in
which case indeed you'll need to generate it first. Simply run:
`./tools/gen-deps.sh > package/deps.mak 2> /dev/null`

The file is included in the release tarball, but I probably should make
a note about this in the README or something though, yes.

**Comment by cavemandaveman** [comment]
`./tools/gen-deps.sh > package/deps.mak 2> /dev/null` worked to generate the file, thank you.

I am using the latest release tarball from https://github.com/jjk-jacky/anopa/releases, not the git repo directly.

**Comment by jjk-jacky** [comment]
Well, that's not really a release tarball, that's an auto-generated one
from github, so it's akin to building from git.

By release tarball I'm referring to the one I make/provide, e.g. [1], as
linked from the website[2]. You should use those instead if you're
gonna build from tarballs, makes things easier as such generated files
will be included, just as man pages are, else you'll need perl/pod2man
in order to generate them.

[1] https://jjacky.com/anopa/anopa-0.4.0.tar.gz
[2] https://jjacky.com/anopa/

**Comment by cavemandaveman** [comment]
Thanks, I'll take a look at that one.

Any plans on making this repo include everything needed to build and/or providing your official release tarball here?

**Comment by jjk-jacky** [comment]
The repo has everything, there's just a few more steps in order to get
there. :)
It's not uncommon when such generated files don't belong in git (since
they're auto-generated) while providing them in release tarball can
make things easier.

I'm not gonna change that, nor put the tarballs in git. There's
already a link to the official website in the README, though maybe a
note in INSTALL about what's needed when building from git could help,
yes.
